namespace NuzlockeTrackerWeb.Components.GameData;

public static class CharacterData
{
    public static List<Character> MasterList = new()
    {
        new Character("Luffy", "One Piece", 1, CharacterTier.Null),
        new Character("PTS Luffy","One Piece", 1, CharacterTier.Null), 
        new Character("PTS Zoro","One Piece", 2, CharacterTier.Null),
        new Character("PTS Sanji","One Piece", 3, CharacterTier.Null),
        new Character("PTS Law","One Piece", 4, CharacterTier.Null),
        new Character("Ace","One Piece", 5, CharacterTier.Null),
        new Character("TS Luffy","One Piece", 6, CharacterTier.Null),
        new Character("TS Zoro","One Piece", 7, CharacterTier.Null),
        new Character("TS Sanji","One Piece", 8, CharacterTier.Null),
        new Character("Kizaru","One Piece", 9, CharacterTier.Null),
        new Character("Akainu","One Piece", 10, CharacterTier.Null),
        new Character("GOD Usopp","One Piece", 11, CharacterTier.Null),
        new Character("Crocodile","One Piece", 12, CharacterTier.Z),
        new Character("Enel","One Piece", 13, CharacterTier.Z),
        new Character("Jinbei","One Piece", 14, CharacterTier.Null),
        new Character("Big Mom","One Piece", 15, CharacterTier.Null),
        new Character("Lucci","One Piece", 16, CharacterTier.Null),
        new Character("Aokiji","One Piece", 17, CharacterTier.Null),
        new Character("Arlong","One Piece", 18, CharacterTier.Null),
        new Character("TS Law","One Piece", 19, CharacterTier.Null),
        new Character("Shanks","One Piece", 20, CharacterTier.Null),
        new Character("Whitebeard","One Piece", 21, CharacterTier.Null),
        new Character("Namek Goku","Dragon Ball", 22, CharacterTier.Null),
        new Character("Android Vegeta","Dragon Ball", 23, CharacterTier.Null),
        new Character("Piccolo","Dragon Ball", 24, CharacterTier.Null),
        new Character("Krillin","Dragon Ball", 25, CharacterTier.Z),
        new Character("Gohan","Dragon Ball", 26, CharacterTier.Z),
        new Character("Buu Goku","Dragon Ball", 27, CharacterTier.Null),
        new Character("Trunks","Dragon Ball", 28, CharacterTier.Z),
        new Character("Caulifla","Dragon Ball", 29, CharacterTier.Null),
        new Character("Majin Vegeta","Dragon Ball", 30, CharacterTier.Null),
        new Character("Vegeto","Dragon Ball", 31, CharacterTier.Null),
        new Character("Frieza","Dragon Ball", 32, CharacterTier.Null),
        new Character("Pui Pui","Dragon Ball", 33, CharacterTier.Null),
        new Character("Perfect Cell","Dragon Ball", 34, CharacterTier.Null),
        new Character("Super Goku","Dragon Ball", 35, CharacterTier.Null),
        new Character("Super Vegeta","Dragon Ball", 36, CharacterTier.Null),
        new Character("Gogeta","Dragon Ball", 37, CharacterTier.Null),
        new Character("Bardock","Dragon Ball", 38, CharacterTier.Z),
        new Character("Jiren","Dragon Ball", 39, CharacterTier.Z),
        new Character("Broly","Dragon Ball", 40, CharacterTier.Null),
        new Character("Goku Black","Dragon Ball", 41, CharacterTier.Null),
        new Character("PTS Naruto","Naruto", 42, CharacterTier.Null),
        new Character("PTS Sasuke","Naruto", 43, CharacterTier.Null),
        new Character("Kakashi","Naruto", 44, CharacterTier.Null),
        new Character("Rock Lee","Naruto", 45, CharacterTier.Null),
        new Character("Neji","Naruto", 46, CharacterTier.Null),
        new Character("Zabuza","Naruto", 47, CharacterTier.Null),
        new Character("Gaara","Naruto", 48, CharacterTier.Null),
        new Character("TS Sasuke","Naruto", 49, CharacterTier.Null),
        new Character("TS Naruto","Naruto", 50, CharacterTier.Null),
        new Character("Itachi","Naruto", 51, CharacterTier.Z),
        new Character("Pain","Naruto", 52, CharacterTier.Z),
        new Character("Guy Sensei","Naruto", 53, CharacterTier.Null),
        new Character("Ay","Naruto", 54, CharacterTier.Null),
        new Character("Kisame","Naruto", 55, CharacterTier.Z),
        new Character("Killer B","Naruto", 56, CharacterTier.Null),
        new Character("War Sasuke","Naruto", 57, CharacterTier.Null),
        new Character("Minato","Naruto", 58, CharacterTier.Null),
        new Character("Madara","Naruto", 59, CharacterTier.Z),
        new Character("PTS Ichigo","Bleach", 60, CharacterTier.Null),
        new Character("Rukia","Bleach", 61, CharacterTier.Null),
        new Character("Shinji","Bleach", 62, CharacterTier.Null),
        new Character("Byakuya","Bleach", 63, CharacterTier.Null),
        new Character("Shunsui","Bleach", 64, CharacterTier.Null),
        new Character("Grimmjow","Bleach", 65, CharacterTier.Null),
        new Character("Gin","Bleach", 66, CharacterTier.Null),
        new Character("Starrk","Bleach", 67, CharacterTier.Z),
        new Character("Toshiro","Bleach", 68, CharacterTier.Null),
        new Character("Ulquiorra","Bleach", 69, CharacterTier.Null),
        new Character("TS Ichigo","Bleach", 70, CharacterTier.Null),
        new Character("Yoruichi","Bleach", 71, CharacterTier.Z),
        new Character("Kenpachi","Bleach", 72, CharacterTier.Null),
        new Character("Aizen","Bleach", 73, CharacterTier.Null),
        new Character("Yhwach","Bleach", 74, CharacterTier.Null),
        new Character("Yamamoto","Bleach", 75, CharacterTier.Z),
        new Character("Kisuke","Bleach", 76, CharacterTier.Null),
        new Character("Rikka","Misc", 77, CharacterTier.Null),
        new Character("Kazuma","Misc", 78, CharacterTier.Null),
        new Character("Afro Samurai","Misc", 79, CharacterTier.Null),
        new Character("Chika","Misc", 80, CharacterTier.Null),
        new Character("Soulja Boy","Misc", 81, CharacterTier.Z),
        new Character("Ryuko","Misc", 82, CharacterTier.Z),
        new Character("Guts","Misc", 83, CharacterTier.Z),
        new Character("Asta","Misc", 84, CharacterTier.Null),
        new Character("Hiei","Misc", 85, CharacterTier.Null),
        new Character("Yusuke","Misc", 86, CharacterTier.Null),
        new Character("Accelerator","Misc", 87, CharacterTier.Z),
        new Character("Misaka","Misc", 88, CharacterTier.Z),
        new Character("Ogun","Misc", 89, CharacterTier.Null),
        new Character("Jin Woo","Misc", 90, CharacterTier.Null),
        new Character("Mob","Misc", 91, CharacterTier.Null),
        new Character("Akira","Misc", 92, CharacterTier.Null),
        new Character("Ragna","Misc", 93, CharacterTier.Z),
        new Character("Maka","Misc", 94, CharacterTier.Null),
        new Character("Alucard","Misc", 95, CharacterTier.Z),
        new Character("Jonathan","Jojo", 96, CharacterTier.Null),
        new Character("Joseph","Jojo", 97, CharacterTier.Null),
        new Character("Jotaro","Jojo", 98, CharacterTier.Null),
        new Character("Old Joseph","Jojo", 99, CharacterTier.Null),
        new Character("Josuke","Jojo", 100, CharacterTier.Null),
        new Character("Giorno","Jojo", 101, CharacterTier.Null),
        new Character("Kira","Jojo", 102, CharacterTier.Z),
        new Character("Jolyne","Jojo", 103, CharacterTier.Null),
        new Character("Pucci","Jojo", 104, CharacterTier.Null),
        new Character("Hol Horse","Jojo", 105, CharacterTier.Null),
        new Character("Ghiacchio","Jojo", 106, CharacterTier.Null),
        new Character("Okuyasu","Jojo", 107, CharacterTier.Null),
        new Character("Kars","Jojo", 108, CharacterTier.Null),
        new Character("Weather Report","Jojo", 109, CharacterTier.Z),
        new Character("Rissoto","Jojo", 110, CharacterTier.Null),
        new Character("Speedwagon","Jojo", 111, CharacterTier.Null),
        new Character("Dio","Jojo", 112, CharacterTier.Null),
        new Character("Doppio","Jojo", 113, CharacterTier.Null),
        new Character("Gon","HXH", 114, CharacterTier.Null),
        new Character("Killua","HXH", 115, CharacterTier.Null),
        new Character("Hisoka","HXH", 116, CharacterTier.Null),
        new Character("Illumi","HXH", 117, CharacterTier.Null),
        new Character("Chrollo","HXH", 118, CharacterTier.Null),
        new Character("Kurapika","HXH", 119, CharacterTier.Null),
        new Character("Ikalgo","HXH", 120, CharacterTier.Null),
        new Character("Uvogin","HXH", 121, CharacterTier.Null),
        new Character("Morel","HXH", 122, CharacterTier.Null),
        new Character("Yuji","JJK", 123, CharacterTier.Z),
        new Character("Gojo","JJK", 124, CharacterTier.Z),
        new Character("Todo","JJK", 125, CharacterTier.Null),
        new Character("Sukuna","JJK", 126, CharacterTier.Null),
        new Character("Choso","JJK", 127, CharacterTier.Null),
        new Character("Geto","JJK", 128, CharacterTier.Null),
        new Character("Nanami","JJK", 129, CharacterTier.Null),
        new Character("Toji","JJK", 130, CharacterTier.Null),
        new Character("Deku","MHA", 131, CharacterTier.Null),
        new Character("Bakugo","MHA", 132, CharacterTier.Null), 
        new Character("All Might","MHA", 133, CharacterTier.Null),
        new Character("Todoroki","MHA", 134, CharacterTier.Null),
        new Character("Iida","MHA", 135, CharacterTier.Null),
        new Character("Endeavor","MHA", 136, CharacterTier.Null),
        new Character("Lemillion","MHA", 137, CharacterTier.Null),
        new Character("Tokoyami","MHA", 138, CharacterTier.Null),
        new Character("Vigilante Deku","MHA", 139, CharacterTier.Null),
        new Character("Shirou","Fate", 140, CharacterTier.Null),
        new Character("Saber","Fate", 141, CharacterTier.Null),
        new Character("Gilgamesh","Fate", 142, CharacterTier.Null),
        new Character("Kiritsugu","Fate", 143, CharacterTier.Null),
        new Character("Lancer","Fate", 144, CharacterTier.Null),
        new Character("Iskandar","Fate", 145, CharacterTier.Null),
        new Character("Ishtar","Fate", 146, CharacterTier.Z),
        new Character("Mash","Fate", 147, CharacterTier.Null),
        new Character("Illya","Fate", 148, CharacterTier.Z),
        new Character("Natsu","Fairy Tail", 149, CharacterTier.Null),
        new Character("Gray","Fairy Tail", 150, CharacterTier.Null),
        new Character("Erza","Fairy Tail", 151, CharacterTier.Null),
        new Character("Denji","CSM", 152, CharacterTier.Null),
        new Character("Aki","CSM", 153, CharacterTier.Null),
        new Character("Power","CSM", 154, CharacterTier.Null),
        new Character("Tanjiro","Demon Slayer", 155, CharacterTier.Null),
        new Character("Rengoku","Demon Slayer", 156, CharacterTier.Null),
        new Character("Tengen","Demon Slayer", 157, CharacterTier.Null),
        new Character("Kokushibo","Demon Slayer", 158, CharacterTier.Null),
        new Character("Ohma","Prestige", 159, CharacterTier.Null),
        new Character("Zenitsu","Prestige", 160, CharacterTier.Null),
        new Character("Shisui","Prestige", 161, CharacterTier.Null),
        new Character("Tobi","Prestige", 162, CharacterTier.Null),
        new Character("Satsuki","Prestige", 163, CharacterTier.Null),
        new Character("Achilles","Prestige", 164, CharacterTier.Null),
        new Character("Zamasu","Prestige", 165, CharacterTier.Null),
        new Character("Deidara","Prestige", 166, CharacterTier.Z),
        new Character("Super Dummy","Prestige", 167, CharacterTier.Null),
        new Character("Mr Satan","Prestige", 168, CharacterTier.Null),
        new Character("Shadow Dio","Prestige", 169, CharacterTier.Null),
        new Character("Mr President","Prestige", 170, CharacterTier.Z),
        new Character("Kirito","SAO", 171, CharacterTier.Null),
        new Character("Asuna","SAO", 172, CharacterTier.Null),
        new Character("Sinon","SAO", 173, CharacterTier.Null),
        new Character("Saitama","OPM", 174, CharacterTier.Null),
        new Character("Tatsumaki","OPM", 175, CharacterTier.Null),
        new Character("Metal Bat","OPM", 176, CharacterTier.Null),
        new Character("Roland","Project Moon", 177, CharacterTier.Null),
        new Character("Ricardo","Project Moon", 178, CharacterTier.Null),
        new Character("Snake","MGS", 179, CharacterTier.Null),
        new Character("Raiden","MGS", 180, CharacterTier.Null),
        new Character("Netero","HXH", 181, CharacterTier.Null),
        new Character("Meruem","HXH", 182, CharacterTier.Z),
        new Character("Jogo","JJK", 183, CharacterTier.Null),
        new Character("Edward Elric","Misc", 184, CharacterTier.Null),
        new Character("Boa Hancock","One Piece", 185, CharacterTier.Null),
        new Character("Wano Law","One Piece", 186, CharacterTier.Null),
        new Character("2B","Anime?", 187, CharacterTier.Null),
        new Character("Shadow Dummy","Anime?", 188, CharacterTier.Null),
        new Character("Raiden 2","MGS", 189, CharacterTier.Null)
    };
}
